---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - main

steps:
- name: build_image_PR
  image: plugins/docker
  settings:
    dry_run: true
    repo: rustycl0ck/drone-github-comment
  when:
    event:
    - pull_request

- name: test
  image: golang
  settings:
    app_id:
      from_secret: test_app_id
    rsa_key:
      from_secret: test_rsa_key
  commands:
    - make test
  when:
    event:
    - pull_request

- name: build_image
  image: plugins/docker
  settings:
    auto_tag: true
    repo: rustycl0ck/drone-github-comment
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    event:
    - tag
    - push
---
kind: signature
hmac: fbade69a0f87b9f43746199b68161cc5a6b3e72fe3b3545df713b30d8dd593b2

...
