---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - main

steps:
- name: build_image_PR
  image: plugins/docker
  settings:
    dry_run: true
    repo: rustycl0ck/drone-pr-comment
  when:
    event:
    - pull_request

- name: test
  image: golang
  settings:
    app_id:
      from_secret: test_app_id
    rsa_key:
      from_secret: test_rsa_key
  commands:
    - make test
  when:
    event:
    - pull_request

- name: build_image
  image: plugins/docker
  settings:
    auto_tag: true
    repo: rustycl0ck/drone-pr-comment
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    event:
    - tag
    - push
---
kind: signature
hmac: 06ad83d4f3010b6a4233dbc5777883d49248afe488d7cf9711fc55ae8b2c7173

...
